### PR TITLE
Subtask #901: Refactor station properties to use movable dialog

### PR DESCRIPTION
**Pull request by j-hha**
Station properties component now uses the new movable dialog component.

Ticket #901

### CODE REVIEW

**Review by ruegenbfr — CHANGES_REQUESTED** [review]
Well done! Only `mat-dialog-content` is missing

**Comment by j-hha** [comment]
> Well done! Only `mat-dialog-content` is missing

- [ ] add scroll area `mat-dialog-content`

**Review by ruegenbfr — CHANGES_REQUESTED** [review]
Please remove the 
```
.fcl-drag-handle {
...
}
```
in file
`src/app/tracing/dialog/station-properties/station-properties.component.scss`
it should be obsolet.

**Comment by j-hha** [comment]
> Please remove the
> 
> ```
> .fcl-drag-handle {
> ...
> }
> ```
> 
> in file `src/app/tracing/dialog/station-properties/station-properties.component.scss` it should be obsolet.

- [ ] remove unused scss

**Pull request merged**
